name: Check PR dependencies on merge

on:
  pull_request:
    types: [closed]

jobs:
  check_dependencies:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check PR dependencies
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            function extractPRNumbers(text) {
              const regex = /#(\d+)/g;
              let matches;
              let prNumbers = new Set();
              while ((matches = regex.exec(text)) !== null) {
                prNumbers.add(parseInt(matches[1]));
              }
              return Array.from(prNumbers);
            }

            console.log('Fetching open draft PRs...');

            const draftPRs = await github.rest.pulls.list({
              owner,
              repo,
              state: 'open',
              per_page: 100,
            });

            const draftPRsFiltered = draftPRs.data.filter(pr => pr.draft === true);
            console.log(`Found ${draftPRsFiltered.length} draft PR(s).`);

            async function isPRMergedOrClosed(prNumber) {
              try {
                const pr = await github.rest.pulls.get({
                  owner,
                  repo,
                  pull_number: prNumber,
                });
                return pr.data.merged || pr.data.state === 'closed';
              } catch (error) {
                console.log(`Error fetching PR #${prNumber}: ${error.message}`);
                return false;
              }
            }

            for (const pr of draftPRsFiltered) {
              console.log(`Checking draft PR #${pr.number} - ${pr.title}`);

              const body = pr.body || '';
              const dependencies = extractPRNumbers(body);

              if (dependencies.length === 0) {
                console.log(`No dependencies found for PR #${pr.number}, skipping.`);
                continue;
              }

              console.log(`Dependencies for PR #${pr.number}: ${dependencies.join(', ')}`);

              const checks = await Promise.all(dependencies.map(isPRMergedOrClosed));
              const allMet = checks.every(status => status === true);

              if (allMet) {
                console.log(`All dependencies met for PR #${pr.number}.`);

                const commentBody = `:white_check_mark: All dependencies for this draft PR are now merged or closed. You can proceed when ready.`;

                const comments = await github.rest.issues.listComments({
                  owner,
                  repo,
                  issue_number: pr.number,
                });

                const alreadyCommented = comments.data.some(c => c.body === commentBody);

                if (!alreadyCommented) {
                  await github.rest.issues.createComment({
                    owner,
                    repo,
                    issue_number: pr.number,
                    body: commentBody,
                  });
                  console.log(`Comment posted on draft PR #${pr.number}.`);
                } else {
                  console.log(`Comment already exists on draft PR #${pr.number}, not posting again.`);
                }
              } else {
                console.log(`Not all dependencies are met for PR #${pr.number}, skipping comment.`);
              }
            }

            console.log('Dependency check completed.');

